# Host to use for canonical URL generation (without trailing slash)
host: https://venusbb.github.io/Digital-Handbook
service_link: https://venusbb.github.io/Digital-Handbook

# Header-related options
show_govuk_logo: false
service_name: Cabinet Office Digital Handbook
description: Guides to understanding and implementing Cabinet Office digital policies, standards, principles, strategies, guidance, and blueprints

# Links to show on right-hand-side of header
header_links:
  GitHub: https://github.com/cabinetoffice/CO-Digital-Handbook

footer_links:
  Accessibility: /accessibility.html

enable_search: true

# Tracking ID from Google Analytics (e.g. UA-XXXX-Y)
# ga_tracking_id: UA-111409592-1

# Table of contents depth – how many levels to include in the table of contents.
# If your ToC is too long, reduce this number and we'll only show higher-level
# headings.
max_toc_heading_level: 6

# Prevent robots from indexing (e.g. whilst in development)
prevent_indexing: false

show_contribution_banner: true
github_repo: cabinetoffice/CO-Digital-Handbook
github_branch: main

# Ownership for page reviews
default_owner_slack: '#cabinetofficedigital'
owner_slack_workspace: Digital-Handbook

# Are these still needed?
redirects:
  /standards/publish-opensource-code.html: /standards/source-code/index.html#publish-open-source-code
  /standards/git.html: /standards/source-code/working-with-git.html
  /standards/testing-with-rspec.html: /manuals/programming-languages/ruby.html#testing-with-rspec
  /standards/secrets-ACL.html: /standards/secrets-acl.html
